### ISSUE TITLE
Cache objects with transport-encoding compression compressed

### ISSUE THREAD

**Issue by Mic92** [kalbasit/ncps#62]
Binary caches such as harmonia will use http-level compression indicated by the `Content-Encoding: zstd`. It should not to hard in this case to just store the compressed data as is and than serve compressed content. This would safe re-compression. This would make it easy to have your CI server running a local binary cache that is than cached by ncps.

**Comment by kalbasit** [comment]
It's pretty easy to implement a compression, using Chi's [Compress middleware](https://pkg.go.dev/github.com/go-chi/chi/v5@v5.1.0/middleware#Compress) however, I didn't add it because I was thinking that all nar files are already compressed so there won't be much benefit to compress them further. ncps stores nar files as-is, it does not mutate them, compress them or de-compress them. I have not played with Harmonia yet, do you see any benefits from compressing with `zstd` the compressed nar archives?

**Comment by Mic92** [comment]
You wouldn't need any middleware, but you would need to have an http client that doesn't de-compress already compressed data:

Let's say you get this:

```
HTTP/1.1 200 OK
Date: mon, 26 June 2016 22:38:34 GMT
...
Content-Encoding: zstd
```

You would store the compressed file as is without de-compressing, store "zstd" as the compression and maybe update the length field of the file based on your implementation.

**Comment by Mic92** [comment]
ZSTD compression provides speed-up in harmonia. In my measurements it's still faster if you have a local 1Gbit/s connection. The lower your bandwidth or peering, the better it performs.

**Comment by kalbasit** [comment]
> You wouldn't need any middleware, but you would need to have an http client that doesn't de-compress already compressed data:
> 
> Let's say you get this:
> 
> ```
> HTTP/1.1 200 OK
> Date: mon, 26 June 2016 22:38:34 GMT
> ...
> Content-Encoding: zstd
> ```
> 
> You would store the compressed file as is without de-compressing, store "zstd" as the compression and maybe update the length field of the file based on your implementation.

Sounds like too much work, and I'm not sure what would be the benefit of storing re-compressed nars as opposed to relying on ncps to honor the `Accept-Encoding` header from incoming requests and either compress them or not.

**Comment by kalbasit** [comment]
> ZSTD compression provides speed-up in harmonia. In my measurements it's still faster if you have a local 1Gbit/s connection. The lower your bandwidth or peering, the better it performs.

I see, so simply honoring `Accept-Encoding` would give you what you need, right?

**Comment by Mic92** [comment]
You can also use `Accept-Encoding`, however this is a bit more trickier, because you might have to decompress already compressed content in case your http client doesn't implement it. You would also than need to set `Content-Encoding` on the server side. Overall it seems more complex to me to implement it this way. You also don't want to compress on the fly unless you can avoid it. Serving compressed content will be always faster than on-the-fly compression and more cache-efficient. Especially once you want to scale up to 10Gbits/s.

**Comment by kalbasit** [comment]
What you're suggesting is doing something like the following?
- Receive narfile from upstream, narfile most likely will have `Compression: xz`and a URL ending in `.nar.xz`
- Download the `nar.xz`
- Extract its contents and re-pack it as `.nar.zst`
- Store it in the cache.
- Mutate the narfile:
  - update URL to end with `.nar.zst`
  - update the `FileSize` to match the size of the new `.nar.zst` file.
  - update the `FileHash` to match the new `.nar.zst` file.
  - This is uncharted for me, but does the signature from upstream still matches or needs to be removed?
- finally store the narinfo, it's ready.

**Comment by Mic92** [comment]
Ah sorry, I think there is a misunderstanding if your upstream narinfo already has `Compression: xz`, you don't need to do anything different from what you do today.
Of course you could re-compress it as zstd for faster decompression speed, but it seems overall not so useful.

However if you have files requested from harmonia, they will have no compression field set in the narinfo. Instead harmonia will set the `Content-Encoding` header to zstd if your own http client advertises this with the `Accept-Encoding` header. If ncps is smart about this, it would skip decompressing the content-encoding and just store the compressed file and update it's local narinfo file to contain `Compression: zstd`.

Compression doesn't affect the signature of a narinfo. The signature is done over the nar file instead: https://github.com/nix-community/harmonia/blob/997ec02589d1dfacf1cb6874ba943b961d63d530/src/narinfo.rs#L85

**Comment by kalbasit** [comment]
Ah, that makes sense now. That's the reason why I was so confused, and I was asking questions trying to clarify why do we need to compress an already-compressed nar.

I don't have experience with Harmonia, so I did not know about the lack of compression; I'm curious why does it work that way? In my experience the nix store uploads to the cache in xz so why change that and serve them un-compressed? Anyways, I'll go ahead and setup my own instance of Harmonia on my cluster and will test it out and integrate support for it.

**Comment by Mic92** [comment]
If you compress on nar level you cannot provide the size of the downloaded content to your client. This messes up the download progress bar. Harmonia and also if you would set up nix-serve{,-ng} with nginx + compression, serve data directly from the /nix/store and therefore cannot predict how large the transfer would be after compression.

**Comment by Mic92** [comment]
Actually ncps + harmonia could be a good combination. This way you don't need to populate a binary cache upfront, which increases latency in CI and still get could performance for content that is actually downloaded.

**Comment by Mic92** [comment]
Ah. Forgot to mention builtin zstd compression was just added recently: https://github.com/NixOS/nixpkgs/pull/362948
I was using nginx before that for this feature.

**Comment by kalbasit** [comment]
@Mic92 This is now implemented, do you think you can give it a try?

**Comment by kalbasit** [comment]
@Mic92 did you get a chance to try it out?

**Comment by Mic92** [comment]
Sorry, I did end up dogfooding https://github.com/numtide/nixos-passthru-cache over christmas
as I want to provide this as a simple solution for providers (i.e. Hetzner) to cache nix in their own datacenters. My plan is however to also deploy ncps after I had a chat with Hetzner.
