### ISSUE TITLE
Use directory sharding

### ISSUE THREAD

**Issue by Mic92** [kalbasit/ncps#63]
Since it's still early into the project, I would recommend to shared directories before you have too many users and need to migrate. Reason is that big directories with a lot of entries will perform worse than smaller directories.

Sharding means that we take the first few characters of a path as the subdirectories:

So:

```
/nix/store/k48bha2fjqzarg52picsdfwlqx75aqbb-coreutils-9.5
```

will be stored as:

```
./your-cache/k/k4/k48bha2fjqzarg52picsdfwlqx75aqbb-coreutils-9.5
```

This is the algorithm implemented by the wikipedia image upload and I also ported it to attic.

**Comment by Mic92** [comment]
Here some pseudo code:

```go
func (c *Config) GetPath(p string) string {
	level1 := p[:1]
	level2 := p[:2]
	return filepath.Join(c.Path, level1, level2, p)
}
```

**Comment by kalbasit** [comment]
Makes sense, thanks for the suggestion!
